#!/bin/sh
. /etc/functions.sh

config_load pitcher

bat(){
    local servo_path
    config_get servo_path $1 servo_path
    batter $servo_path
}

if [ "$ACTION" = "released" -a "$BUTTON" = "BTN_1" ]; then
    broker_user=`config_get mqtt username`
    broker_password=`config_get mqtt password`

    local host, port, topic_root, name

    config_get host mqtt host
    config_get port mqtt port
    config_get topic_root mqtt topic_root
    config_get name mqtt name

    if hash mosquitto_pub 2>/dev/null; then
	mosquitto_pub "--host $host --port $port --message released --topic $topic_root$name/button"
    else
	logger -p user.warn "Pitcher button pressed but moquitto_pub doesn't exist"
    fi

    if hash batter 2>/dev/null; then
	local servoconfig_get
	config_foreach bat batter
    else
	logger -p user.warn "Pitcher button pressed but no batter to pitch to!"
    fi
fi
